### ISSUE TITLE
is @functools.cache on next_* really works?

### ISSUE THREAD

**Issue by leshabirukov** [HeWeMel/nographs#2]
Greetings!
Well, now it is my turn to bother you.
from here:
https://nographs.readthedocs.io/en/latest/graph_operations.html#graph-pruning-abstraction-multiplication-union-and-intersection:~:text=home_position%20%3D%20(,(goals))
one can guess subj should.
but look at this test:
https://github.com/leshabirukov/nographs/blob/cache_issue_0/contrib/nog_cache_issue.ipynb
Looks like one need additional wrap to work. I suspect the `traversal` parameter. Wrapping did fine (in case you actually don't need this parameter!), if user knows about all this. May be there is some way to say `cache` to exclude second parameter?
Alexey

**Comment by HeWeMel** [comment]
Thanks for your question and your analysis.

You refer to an example in the documentation of the library. There, function _next_vertices_pos_ has been wrapped by _@functools.cache_, in the code block you linked. In the code block below the one you linked, [here](https://nographs.readthedocs.io/en/latest/graph_operations.html#graph-pruning-abstraction-multiplication-union-and-intersection:~:text=next_vertices_pos(position%2C%20None)), you can see that the function is called as follows: `next_vertices_pos(position, None)`, and like this, the caching works. This matches your code variant with `forward = forward_2`, where the caching also works: you call the cache-wrapped function _forward_1_ by function _forward_2_ with _None_ as second parameter.

From the first view I would say, your other test variant, where the cache-wrapped function _forward_1_ is called with the traversal object as second parameter, has two problems, and maybe I can learn two different things from it:

1) You create three different traversal objects instead of restarting the first one. So, your _@functools.cache_ gets calls with three different second arguments. It cannot reuse results between these groups of calls. This might not be surprising for the users who read the section before the example, [search-aware-graphs](https://nographs.readthedocs.io/en/latest/graphs_and_adaptation.html#search-aware-graphs), where it is described, what this second parameter is: the traversal; and this object changes in your code from run to run. But I do not want to assume that users read the tutorial section by section. Thus, I will adapt the documentation accordingly.

2) It seems like your caching does not even work within the first traversal, as you get two more dictionary look-ups. I had expected this to work, although I have never tried, because the Python documents of method [__hash__](https://docs.python.org/3/reference/datamodel.html?highlight=__hash__#object.__hash__) says: "User-defined classes have eq() and __hash__()] methods by default; with them, all objects compare unequal (except with themselves) and x.__hash__() returns an appropriate value such that x == y implies both that x is y and hash(x) == hash(y).". This means, as a single traversal object is used as parameter during the first run, this constant second parameter should not disturb the caching. Interesting. I will look into this more deeply.

**Comment by leshabirukov** [comment]
Thanks! I'll try variant with restarting on more complex example, there I initially encountered the issue.
As about 'two more dictionary look-ups' May be it is actually `forward_2` have two calls cached in the cell [3] at the

    forward(0,None)
    forward(2,None)

**Comment by HeWeMel** [comment]
I think I found the reason for problem 2: The implementation of BFS in the library uses two copies of the traversal object, and it switches between the two in order to speed up context switches (reduce attribute changes). This disturbs your caching in the case where the traversal (in fact: the two different traversals) occur as second argument. I will look into this more deeply. If this really is the problem, I have a second reason to add a warning in the documentation, that the caching with _@functools.cache_ only works if the traversal is not used as argument.

**Comment by leshabirukov** [comment]
But I am still curious about excluding `traversal` parameter from caching. There are libs like `cachetools` for that, but is excluding safe? When it could broke graph or traversals?

**Comment by HeWeMel** [comment]
I have done some tests to verify my assumptions about the reasons why the caching by @functools.cache does not work in your code. Please find them here, if you are interested:

[nog_cache_issue-test2.zip](https://github.com/HeWeMel/nographs/files/13058569/nog_cache_issue-test2.zip)

**Comment by HeWeMel** [comment]
Here are the cases that I have tested:

**1)  DFS or BFS, separate traversal objects for each traversal, caching with traversal as second argument**
--> Cache does not work.
Reason: Within a single traversal run, NoGraphs asks at most once for the next_vertices of each vertex. So, the cache does not 
help. And between different traversals, the different second arguments (different traversal objects) to the function decorated with @functools.cache prevent the caching for working.

**2) DFS or BFS, separate traversal objects for each traversal, caching with None as second argument**
--> Cache works and caches graph data between traversal runs
Reason:  All calls to the function decorated with @functools.cache have identical second arguments: None.

**3a) DFS, just one traversal object for several runs, caching with traversal as second argument**
-> Cache works and caches graph data between traversal runs
Reason: All calls  to the function decorated with @functools.cache have identical second arguments: the (single) traversal object.

**3b) BFS,  just one traversal object for several runs, caching with different traversal objects (see reason below!) as second argument**
--> Cache does not work.
Reason: Within a single traversal run, NoGraphs asks at most once for the next_vertices of each vertex. So, the cache does not 
help. And between different traversals, the arguments for the second parameter to the function decorated with @functools.cache differ, and prevent the caching for working: In each traversal run, BFS calls the next_vertices function with different traversal objects. In NoGraphs, BFS differs from DFS in this point.

**Comment by HeWeMel** [comment]
I plan to change the documentation in the following points:

- [Search-aware graphs, second argument of next_vertices functions](https://nographs.readthedocs.io/en/latest/graphs_and_adaptation.html#search-aware-graphs:~:text=you%20get%20the%20current%20traversal%20as%20second%20parameter): "You get a (!) traversal object... Note: This can be another object as the one you used to start the traversal with."
- [Code and tip for graph materialization](https://nographs.readthedocs.io/en/latest/graph_operations.html#:~:text=Together%20with%20the,avoid%20repeated%20computations.): Although the example works perfectly, and I correctly use None as second parameter of the cached function, I remove the second parameter of function *next_vertices_pos* and document in the tip, that "@functools.cache should not be used on functions called by NoGraphs with traversal objects as second parameter. Reason: The caching should not depend on the individual traversal run, otherwise, I will not work as expected. Note: Even when you start several runs with the same traversal object, the next_vertices function can be called by NoGraphs with different traversal objects as second parameter."
- [API, next vertices and next edges functions](https://nographs.readthedocs.io/en/latest/api.html#next-vertices-and-next-edges-functions): I add: "Note: Even when you start several runs with the same traversal object, the next_vertices function can be called by NoGraphs with different traversal objects as second parameter."

**Comment by leshabirukov** [comment]
Great! I suppose, interaction with functools caching is now clarified, closing issue. Brief explanation of where it come from: I am now wrapping `onnx`(protobuf) graphs for inspection and manipulation, trying do as little infra work as possible using `nographs`.  Similar to bringing indexation to `sql` tables. I expect to research more about caching, it probably will take some time.  
Thank you for thoughtful response!  
Also, while experimenting with `nographs`, I make some examples for it, you can find it in my `dev` branches, possibly, I'll also add some utilities. All my changes is in `contrib` folder for now, would be great, if you have a look, if it satisfy your `nographs` vision, consider pulling it to main repo, I open to discuss form, style etc.

**Comment by HeWeMel** [comment]
The new version of the documentation is live. The adaptions can be found here:
- [More detailed description of the second parameter of the callback functions](https://nographs.readthedocs.io/en/latest/graphs_and_adaptation.html#search-aware-graphs:~:text=you%20get%20a,a%20separate%20object.))
- [Better description of the caching](https://nographs.readthedocs.io/en/latest/graph_operations.html#:~:text=Line%20%40functools.cache,of%20being%20reused.)
- [Example function with only one parameter (less misleading)](https://nographs.readthedocs.io/en/latest/graph_operations.html#:~:text=def%20next_positions_with_distances(pos))

**Comment by HeWeMel** [comment]
(I read through your examples. Please find my thoughts about some topics in the new issues that I have created.
Your application context is very interesting. I wish you pleasure and good success with your project.)

**Comment by leshabirukov** [comment]
I suggest to turn on `your repo -> settings -> discussions`. It is more suitable for, namely, discussions.
